

/* 1) Référentiels */
CREATE TABLE IF NOT EXISTS CAUSE_ANOMALIE (
  ID_CAUSE   INT AUTO_INCREMENT PRIMARY KEY,
  CODE       VARCHAR(30) NOT NULL UNIQUE,
  LIBELLE    VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SEVERITE_ANOMALIE (
  ID_SEVERITE INT AUTO_INCREMENT PRIMARY KEY,
  CODE        VARCHAR(20) NOT NULL UNIQUE,
  LIBELLE     VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

INSERT IGNORE INTO CAUSE_ANOMALIE (CODE, LIBELLE) VALUES
('USURE','Usure normale'),('CHOC','Choc/Accident'),
('FAB','Défaut fabrication'),('ELECT','Panne électrique'),
('MOTEUR','Problème moteur');

INSERT IGNORE INTO SEVERITE_ANOMALIE (CODE, LIBELLE) VALUES
('MINEURE','Impact faible'),('MAJEURE','Impact notable'),('CRITIQUE','Arrêt immédiat');

/* 2) Colonnes à ajouter dans PANNE
   -> Si certaines existent déjà, ces ALTER échoueront. Dans ce cas, exécute seulement celles qui manquent. */
ALTER TABLE PANNE ADD COLUMN ID_VEHICULE INT NULL;
ALTER TABLE PANNE ADD COLUMN ID_CAUSE INT NULL;
ALTER TABLE PANNE ADD COLUMN ID_SEVERITE INT NULL;
ALTER TABLE PANNE ADD COLUMN COUT_PIECES DECIMAL(10,2) NULL;
ALTER TABLE PANNE ADD COLUMN COUT_MAIN_OEUVRE DECIMAL(10,2) NULL;
ALTER TABLE PANNE ADD COLUMN COUT_IMMOBILISATION DECIMAL(10,2) NULL;
ALTER TABLE PANNE ADD COLUMN DATE_RESOLUTION DATE NULL;
ALTER TABLE PANNE ADD COLUMN STATUT ENUM('ouverte','en_cours','resolue') NULL DEFAULT 'ouverte';

/* 3) Renseigner ID_VEHICULE via INTERROMPRE -> TRAJET (si manquant) */
UPDATE PANNE p
JOIN INTERROMPRE i ON i.ID_PANNE_ = p.ID_PANNE_
JOIN TRAJET t      ON t.ID_TRAJET = i.ID_TRAJET
SET p.ID_VEHICULE = t.ID_VEHICULE
WHERE p.ID_VEHICULE IS NULL;

/* 4) Valeurs par défaut pour éviter les NULL */
SET @ID_CAUSE_DEF    = (SELECT ID_CAUSE    FROM CAUSE_ANOMALIE    WHERE CODE='USURE'   LIMIT 1);
SET @ID_SEVERITE_DEF = (SELECT ID_SEVERITE FROM SEVERITE_ANOMALIE WHERE CODE='MINEURE' LIMIT 1);

UPDATE PANNE
SET
  ID_CAUSE            = COALESCE(ID_CAUSE,    @ID_CAUSE_DEF),
  ID_SEVERITE         = COALESCE(ID_SEVERITE, @ID_SEVERITE_DEF),
  COUT                = COALESCE(COUT, 0),
  COUT_PIECES         = COALESCE(COUT_PIECES, 0),
  COUT_MAIN_OEUVRE    = COALESCE(COUT_MAIN_OEUVRE, 0),
  COUT_IMMOBILISATION = COALESCE(COUT_IMMOBILISATION, 0),
  STATUT              = COALESCE(STATUT, 'ouverte');

/* 5) Index & FK (ajoute-les si pas déjà là) */
CREATE INDEX idx_panne_veh_date ON PANNE (ID_VEHICULE, DATE);

ALTER TABLE PANNE
  ADD CONSTRAINT fk_panne_vehicule  FOREIGN KEY (ID_VEHICULE)  REFERENCES VEHICULE(ID_VEHICULE);
ALTER TABLE PANNE
  ADD CONSTRAINT fk_panne_cause     FOREIGN KEY (ID_CAUSE)     REFERENCES CAUSE_ANOMALIE(ID_CAUSE);
ALTER TABLE PANNE
  ADD CONSTRAINT fk_panne_severite  FOREIGN KEY (ID_SEVERITE)  REFERENCES SEVERITE_ANOMALIE(ID_SEVERITE);

/* 6) Rendre NOT NULL (après backfill) */
ALTER TABLE PANNE
  MODIFY ID_VEHICULE INT NOT NULL,
  MODIFY ID_CAUSE INT NOT NULL,
  MODIFY ID_SEVERITE INT NOT NULL,
  MODIFY STATUT ENUM('ouverte','en_cours','resolue') NOT NULL DEFAULT 'ouverte',
  MODIFY COUT DECIMAL(10,2) NOT NULL DEFAULT 0,
  MODIFY COUT_PIECES DECIMAL(10,2) NOT NULL DEFAULT 0,
  MODIFY COUT_MAIN_OEUVRE DECIMAL(10,2) NOT NULL DEFAULT 0,
  MODIFY COUT_IMMOBILISATION DECIMAL(10,2) NOT NULL DEFAULT 0;

/* 7) Vue analytique (si tu ne la mets pas dans 002_*) */
CREATE OR REPLACE VIEW V_PANNE_ANALYTIQUE AS
SELECT
  p.ID_PANNE_         AS id_panne,
  p.ID_VEHICULE       AS id_vehicule,
  v.IMMATRICULATION   AS immatriculation,
  p.DESCRIPTION,
  p.DATE              AS date_evt,
  p.STATUT,
  c.LIBELLE           AS cause,
  s.LIBELLE           AS severite,
  COALESCE(p.COUT,0)
  + COALESCE(p.COUT_PIECES,0)
  + COALESCE(p.COUT_MAIN_OEUVRE,0)
  + COALESCE(p.COUT_IMMOBILISATION,0) AS cout_total
FROM PANNE p
LEFT JOIN VEHICULE v          ON v.ID_VEHICULE  = p.ID_VEHICULE
LEFT JOIN CAUSE_ANOMALIE c    ON c.ID_CAUSE     = p.ID_CAUSE
LEFT JOIN SEVERITE_ANOMALIE s ON s.ID_SEVERITE  = p.ID_SEVERITE;
